### ISSUE TITLE
MatchOneToN method times out

### ISSUE THREAD

**Issue by wezzix** [unosquare/wsfingerprint#21]
**Describe the bug**
When calling `MatchOneToN`, the method times out after 60 seconds and returns an error.

**To Reproduce**
Run the sample app and press `E`, `W`.
The device beeps once.
Wait 60 seconds. An error is returned.

**Expected behavior**
The method should wait indefinetly, or until a finger is read. Otherwise, because we don't know when the user will be present, you would have to call the method each 60 seconds with an annoying beep each time.

**Additional context**
To implement access control using the fingerprint reader, as I understand, you are supposed to call `MatchOneToN` and wait, possibly indefinetly for a response. How else are we to support the scenario when we are waiting around the clock for a user to use the device?
A resolution would be to remove `AcquireTimeout` from the `MatchOneToN` method, or use `TimeSpan.MaxValue`, or make it configurable.
Those users wishing to use an actual acquire timeout can use the configurable timeout already supported by the device and your framework called `SetCaptureTimeout`. When setting this to 0 (the default), the device waits indefinietly.
Additionally, a `CancellationToken` is already passed into the method whereby a timeout can be set as well.
For consistency, `MatchOneToOne` should probably be changed as well. The other uses of `AcquireTimeout` could possibly remain, although they appear redundant due to the presence of `SetCaptureTimeout`. 
Let me know if you would prefer a PR.

**Comment by geoperez** [comment]
Hello and yes, you can create a PR! Thanks
